# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-21 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripsched', '0002_auto_20180521_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='Guests',
            field=models.ManyToManyField(null=True, related_name='Trips_people', to='tripsched.Users'),
        ),
    ]
